export IndexPage from './IndexPage';
export RootPage from './RootPage';
export AddPage from './AddPage';
export RemovePage from './RemovePage';
export EditPage from './EditPage';
export SearchPage from './SearchPage';
export HomePage from './HomePage';
export PokemonListPage from './PokemonListPage';
export PikaPage from './PikaPage';
